name: Generate RSS

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  build-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Generate RSS
        run: node scripts/generate-rss.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rss.xml
          git commit -m "chore: update RSS feed"
          git push
